### ISSUE TITLE
backup --include visible

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#10]
```
gtasks backup --include visible
```
produces the notification
```
Including hidden tasks
```
It's literally just the notification - the tasks are exported as selected.

**Comment by Resinderate** [comment]
Ah I see, yeah it's just a logging bug. Should we keep the logging in where it is correctly mentioning `Including hidden tasks` or `Not including hidden tasks`? or we can just do the right thing silently?

**Comment by Resinderate** [comment]
It's been updated in `develop` to do the logging version with the correct output, very easy to remove though if that's what we want 👌

**Comment by bjohas** [comment]
That's great!
