### ISSUE TITLE
Backup of tasks that are linked to mail messages do not include the link

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#11]
If the task has a link to a mail message, that link isn't exported to the backup. Would it be possible to add it?

**Comment by Resinderate** [comment]
Yep no problem.

Just to confirm, this is a task which has come from using the "Add to Tasks" button, and then looks like this in the Tasks pane?
![Screen Shot 2019-11-28 at 21 40 31](https://user-images.githubusercontent.com/4006460/69832803-2495a480-1228-11ea-9c1b-f5fbe7874994.png)

Have added this now to the `develop` branch so we have a `links: []` section in each task, and here is what an example one in a backup looks like from the screenshot:
```
{
    "id": "ajlOamYxUGJlQ0Q2SGVfXw",
    "is_completed": false,
    "links": [
        {
            "description": "Stay more organized with Gmail's inbox",
            "link": "https://mail.google.com/mail/#all/16eb3c8e5e4b1067",
            "type": "email"
        }
    ],
    "notes": null,
    "sub_tasks": [],
    "title": "Stay more organized with Gmail's inbox",
    "updated": "2019-11-28T21:35:22.000Z"
},
```

**Comment by bjohas** [comment]
Thank you!

Are there any other fields coming from the API that can be captured?

**Comment by Resinderate** [comment]
Not that I see, their structure for example in this case was that their `links` field only showed up when a task was using that feature. So unless there is another feature like this we have in mind we can't really add it.
