### ISSUE TITLE
gtasks backup --list ABC

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#13]
Would it be possible to add a --list argument, that only backup up the given list?

**Comment by Resinderate** [comment]
Implemented on the `develop` branch. Now has a `--list` option. Used like:
```
$ ./gtasks backup --list "My Tasks"
Backing up!
Backing up 1 of 2 lists.
Including hidden tasks
Adding list to backup: My Tasks
Creating backup in file: backup-2019-11-28T22:34:26.570829.json
```
And if the list is not found:
```
$ ./gtasks backup --list "Fake List"
Backing up!
Could not find any lists with the name 'Fake List' to backup!
```

There is quite a bit of logging in the first case, perhaps that can be reduced if we prefer, is very easy to do 👍

**Comment by bjohas** [comment]
That's all good - we can polish later :)
