### ISSUE TITLE
Add 'due' to backup

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#15]

**Comment by bjohas** [comment]
This may not actually be possible, see https://tasks-backup.appspot.com/
> Google adds features to Tasks, but does not provide access to that information for third-party apps
> The new Tasks allows a user to set a time for a task, and allows for a task to be repeated, but that information is not available via the API, so I cannot export or display the time or repeat info for a task. These features have been available in Tasks since March 2019, but as at October 2019, I am unable to export that data for my users. There is an open issue for this at https://issuetracker.google.com/issues/36759725#comment40

The page also points to: https://github.com/Google-Tasks-Backup/tasks-backup and https://github.com/Google-Tasks-Backup/import-tasks.

**Comment by Resinderate** [comment]
I had a bit of a dig, it looks like the due time might be possible to extract but not the info around the recurrence.

<img width="320" alt="Screen Shot 2020-02-29 at 23 46 41" src="https://user-images.githubusercontent.com/4006460/75616812-fb99ee00-5b4d-11ea-9dd0-54838a69145e.png">

Just to clarify, from the above task I would be able to get the `Mon, March 2` bit about when it's due, but not the fact that it repeats daily at 10am.

Estimate: 1-2hrs including digging time.

**Comment by bjohas** [comment]
The repeat is not really important. The due date is, because it can be used in the script receiving the data. Let me split this issue in two.

**Comment by bjohas** [comment]
There are possibly three times in a task
- Time modified (""updated")
- Time created - not there, otherwise we would have seen it :)
- Due date - remains to be extracted.

**Comment by Resinderate** [comment]
Implemented in the `develop` branch now. Will now see `due` in the output of the backup. Will have an iso format datetime show up like `2020-03-02T00:00:00.000Z` for tasks that have a due time, and be `null` for ones that don't.

**Comment by bjohas** [comment]
Thanks!
