### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#2]
```
gtasks backup
```
download the full set of tasks (from all lists, with all available data/metadata, and including the hierarchical structure of subtasks) and store this in an arbitrary JSON data structure.

**Comment by Resinderate** [comment]
Approach implemented on `develop` branch.

Will go through all open tasks and generate something that looks like this in json:
```
[
    {
        "id": "MTgzMzMxMjEyMTEzNjA3NTk5NjI6MDow",
        "tasks": [
            {
                "id": "ZEFVRHB0NWhHeklrMFJRVw",
                "is_completed": false,
                "notes": "a note",
                "sub_tasks": [
                    {
                        "id": "RTQtejZ5RnhiLUl4UTNMVA",
                        "is_completed": false,
                        "notes": "asd",
                        "sub_tasks": [],
                        "title": "Sub Task",
                        "updated": "2019-11-19T23:00:05.000Z"
                    },
                    {
                        "id": "MTJ5RlpyMzhTOHZ4cTMzVw",
                        "is_completed": false,
                        "notes": null,
                        "sub_tasks": [],
                        "title": "Sub Task 2",
                        "updated": "2019-11-19T22:45:54.000Z"
                    }
                ],
                "title": "Example Task",
                "updated": "2019-11-16T18:46:48.000Z"
            },
            {
                "id": "WkZZQ0xhR2QtVER1azY1Tw",
                "is_completed": false,
                "notes": null,
                "sub_tasks": [],
                "title": "Ronan",
                "updated": "2019-11-16T18:38:47.000Z"
            }
        ],
        "title": "My Tasks",
        "updated": "2019-11-19T23:00:19.348Z"
    },
    {
        "id": "eVliV21zV2phUlRpQmwtaQ",
        "tasks": [
            {
                "id": "NFdxMnV4bGVTdnFzMy1raw",
                "is_completed": false,
                "notes": null,
                "sub_tasks": [],
                "title": "Has something in it now.",
                "updated": "2019-11-19T22:45:29.000Z"
            }
        ],
        "title": "Another List",
        "updated": "2019-11-19T22:45:21.580Z"
    }
]
```
Will go into a file called `backup.json` in the working directory. If there is already one there it will increment to `backup1.json` etc.

Command line interaction looks like:
```
(gtasks) ~/dev/upwork/gtasks (develop) $ ./gtasks backup
Backing up!
Creating backup in file: backup2.json
```
Can add more logging if we like.

**Comment by bjohas** [comment]
Thank you!

 - Regarding logging, it would be useful to show the lists that are being added, to give some user feedback.
 - Would it be possible to add today's date/time (2019-11-19T22:45:29.000Z) rather than increment?
 - Would it be possible to have an option to backup all tasks (including completed / unpurged) tasks ("is_completed": true)? The default should be to back up all tasks, but the option "--visible" or similar would export current "is_completed": false only?

**Comment by Resinderate** [comment]
- Makes sense, have updated it to mention all the list which are being backed up. It looks like:
```
(gtasks) ~/dev/upwork/gtasks (develop) $ ./gtasks backup --include visible
Backing up!
Including hidden tasks
Adding list to backup: My Tasks
Adding list to backup: Another List
Creating backup in file: backup-2019-11-23T00:04:26.931735.json
```
- Yep, I think that's a much better solution to an increment 👍 New output includes isoformat in the name like `backup-2019-11-23T00:04:26.931735.json`
- Yep, so have added a `--include [all|visible Default: all]` option now. The completed ones will now show up by default, we can bring that back to just visible/un-completed tasks with the `--include visible` option.

**Comment by bjohas** [comment]
Thanks @Resinderate !
