### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by chaoscreater** [edtechhub/gtasks#29]
Hi,

I can't figure out how to run this. I cloned it and installed the requirements and pre-requirements via pip. The GTask file itself has no extension, but it looks like it's a Python file? In your project, I can see there is no extension for GTask as well, so how does it know what .exe to associate with in order to run?

I tried to change the extension to .py and run it with Python 3.9, but then I get this:

```
   from tasks.authenticate import authenticate
ImportError: cannot import name 'authenticate' from partially initialized module 'tasks.authenticate' (most likely due to a circular import)
```

**Comment by chaoscreater** [comment]
NVM, I got it working. It seems I can't run in Python IDLE, I have to call it like this:

`py -3 .\gtasks authenticate`

**Comment by bjohas** [comment]
Thanks - glad it's working!
