### ISSUE TITLE
quick add

### ISSUE THREAD

**Issue by bjohas** [edtechhub/gtasks#3]
```
gtasks quickadd --list ABC "text"
```
adds the item "text" to the top of the list "ABC".

**Comment by Resinderate** [comment]
Completed on the `develop` branch.

YouTube video showing how it works. If your list name or title is a single word you can omit the quotes `./gtasks quickadd --list ABC my_title`, but if they have spaces you need the quotes. e.g. `./gtasks quickadd --list "My Tasks" "quick add task"`

https://youtu.be/JL5iVW6zvlU
